# Created by Peter Nagy - February, 2019

AWSTemplateFormatVersion: 2010-09-09
Description: The template brings up a single instance running Wordpress.

Parameters: 
  AllowedSSHRange:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 0.0.0.0/0
    Description: Your allowed SSH IP range (eg 196.172.0.0/32).
    Type: String
  KeyPair:
    Description: Keypair you will use for the Ansible Config host.
    Type: 'AWS::EC2::KeyPair::KeyName'
  InstanceType: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.large
      - m3.medium
      - m4.large
      - m4.xlarge
      - m4.2xlarge
    Description: Micro should be perfectly enough.
  
  WordpressAMI: 
    Type: String
    Default: ami-076cbdf04760e4a41
    Description: Instance AMI for the Wordpress instance.

  EBSVolumeSize:
    Type: Number
    Default: 30
    Description: Specifies the EBS volume size of the instance.

  VPC:
    Type: AWS::EC2::VPC::Id
    Default: ''
    Description: ID of your existing VPC.
  
  WordpressSubnetCIDR:
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.0.0.0/24
    Description: Subnet range for the public subnet (eg 10.0.0.0/24).
    Type: String

Resources: 
  WordpressSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 
        Ref: WordpressSubnetCIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Join
      - ''
      - - !Ref 'AWS::Region'
        - 'a'
      Tags:
      - Key: Name
        Value: wp-subnet
      - Key: Stack
        Value:
            Ref: AWS::StackName

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Stack
          Value:
            Ref: AWS::StackName

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId:
        Ref: IGW
      VpcId:
        Ref: VPC

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Stack
          Value: 
            Ref: AWS::StackName
  
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: 
    - IGW
    - IGWAttachment
    Properties:
      RouteTableId:
        Ref: RouteTable
      GatewayId: 
        Ref: IGW
      DestinationCidrBlock: 0.0.0.0/0

  PublicWordpressSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: RouteTable
      SubnetId:
        Ref: WordpressSubnet
  
  WordpressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Rules that controls traffic to the WP instance
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Ref: AllowedSSHRange
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 433
          ToPort: 433
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  WordpressInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Join
      - ''
      - - !Ref 'AWS::Region'
        - 'a'
      SubnetId:
        Ref: WordpressSubnet 
      BlockDeviceMappings:
        - DeviceName: /dev/xvda    
          Ebs: 
            VolumeType: gp2
            VolumeSize: 
              Ref: EBSVolumeSize
      ImageId:
        Ref: WordpressAMI
      SecurityGroupIds: 
        - Ref: WordpressSecurityGroup
      KeyName:
        Ref: KeyPair
      InstanceType: 
        Ref: InstanceType
      Tags:
      - Key: Name
        Value: wp-instance
      - Key: Stack
        Value:
            Ref: AWS::StackName
Metadata: {}
Mappings: {}